[package]
name = "picture_process_generated"
version = "0.1.0"
edition = "2015"

[lib]
name = "picture_process_generated"
path = "src/lib.rs"
crate-type = ["staticlib"]

[dependencies]
cpp = "0.5"
notify = "6"
libc = "0.2"
image = { version = "0.24", default-features = false, features = ["png"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"



